import { lazy } from 'react';
import { SectionConfig } from '../types/section.types';

export const sectionsConfig: SectionConfig[] = [
  {
    id: 'home',
    label: 'Accueil',
    path: '/',
    icon: 'home',
    description: "Vue d'ensemble et navigation",
    component: lazy(() => import('../pages/Home/HomePage')),
  },
  // Sections futures (commentées pour référence)
  // {
  //   id: 'spec-review',
  //   label: 'Revue des Specs',
  //   path: '/specs',
  //   icon: 'document',
  //   description: 'Valider les spécifications générées par les agents',
  //   component: lazy(() => import('../sections/SpecReview/SpecReviewPage')),
  //   filter: { status: 'spec_to_validate' }
  // },
  // {
  //   id: 'knowledge',
  //   label: 'Connaissances',
  //   path: '/knowledge',
  //   icon: 'book',
  //   description: 'Gérer la base de connaissances',
  //   component: lazy(() => import('../sections/Knowledge/KnowledgePage')),
  // },
  {
    id: 'prompts',
    label: 'Prompts',
    path: '/prompts',
    icon: 'code',
    description: 'Visualiser et modifier les prompts système',
    component: lazy(() => import('../pages/Prompts/PromptListPage')),
  },
  {
    id: 'prompts-create',
    label: 'Créer Prompt',
    path: '/prompts/new',
    component: lazy(() => import('../pages/Prompts/PromptCreatePage')),
    hidden: true,
  },
  {
    id: 'prompts-detail',
    label: 'Détail Prompt',
    path: '/prompts/:id',
    component: lazy(() => import('../pages/Prompts/PromptDetailPage')),
    hidden: true,
  },
  {
    id: 'posts',
    label: 'Posts',
    path: '/post',
    icon: 'share',
    description: 'Gérer les publications réseaux sociaux',
    component: lazy(() => import('../pages/Posts/PostListPage')),
  },
  {
    id: 'posts-create',
    label: 'Créer Post',
    path: '/post/new',
    component: lazy(() => import('../pages/Posts/PostCreatePage')),
    hidden: true,
  },
  {
    id: 'posts-detail',
    label: 'Détail Post',
    path: '/post/:id',
    component: lazy(() => import('../pages/Posts/PostDetailPage')),
    hidden: true,
  },
  {
    id: 'needs',
    label: 'Besoins',
    path: '/need',
    icon: 'clipboard',
    description: 'Gérer les besoins et leur workflow de validation',
    component: lazy(() => import('../pages/Needs/NeedListPage')),
  },
  {
    id: 'needs-create',
    label: 'Créer Besoin',
    path: '/need/new',
    component: lazy(() => import('../pages/Needs/NeedCreatePage')),
    hidden: true,
  },
  {
    id: 'needs-detail',
    label: 'Détail Besoin',
    path: '/need/:id',
    component: lazy(() => import('../pages/Needs/NeedDetailPage')),
    hidden: true,
  },
  {
    id: 'models',
    label: 'Modèles',
    path: '/models',
    icon: 'database',
    description: 'Gérer les modèles de données JSON',
    component: lazy(() => import('../pages/Models/ModelListPage')),
  },
  {
    id: 'models-create',
    label: 'Créer Modèle',
    path: '/models/new',
    component: lazy(() => import('../pages/Models/ModelCreatePage')),
    hidden: true,
  },
  {
    id: 'models-detail',
    label: 'Détail Modèle',
    path: '/models/:id',
    component: lazy(() => import('../pages/Models/ModelDetailPage')),
    hidden: true,
  },
  {
    id: 'applications',
    label: 'Applications',
    path: '/application',
    icon: 'grid',
    description: 'Gérer les applications et leurs fonctionnalités',
    component: lazy(() => import('../pages/Applications/ApplicationListPage')),
  },
  {
    id: 'applications-create',
    label: 'Créer Application',
    path: '/application/new',
    component: lazy(() => import('../pages/Applications/ApplicationCreatePage')),
    hidden: true,
  },
  {
    id: 'applications-detail',
    label: 'Détail Application',
    path: '/application/:id',
    component: lazy(() => import('../pages/Applications/ApplicationDetailPage')),
    hidden: true,
  },
];
